name: image_annotation_plus
description: This library provides an easy-to-use solution for adding image annotation capabilities to Flutter applications. With this library, users can draw shapes, add text, highlight specific areas, and resize annotations within a defined picture zone.
version: 0.0.1
homepage: https://github.com/Priyanshu078/image_annotation_plus

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

example:
  - name: "Simple Example"
    description: "Showing all the possible annotations"
    path: example/main.dart
